### ISSUE TITLE
Error while accessing the application

### ISSUE THREAD

**Issue by mghildiy** [lagom/lagom-java-maven-chirper-example#19]
Hi,

I get following error when I try to access application with: localhost:9000

> ProvisionException: Unable to provision, see the following errors:

1) No implementation for com.lightbend.lagom.javadsl.server.LagomServiceRouter was bound.
  while locating com.lightbend.lagom.javadsl.server.LagomServiceRouter
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router
    for the 1st parameter of play.api.http.JavaCompatibleHttpRequestHandler.<init>(HttpRequestHandler.scala:217)
  while locating play.api.http.JavaCompatibleHttpRequestHandler
  while locating play.api.http.HttpRequestHandler
    for the 6th parameter of play.api.DefaultApplication.<init>(Application.scala:236)
  at play.api.DefaultApplication.class(Application.scala:235)
  while locating play.api.DefaultApplication
  while locating play.api.Application

1 error

I have followed the instructions on READ.md.

How to solve this issue?

**Comment by ignasi35** [comment]
There's an ongoing PR to fix this issue. See #18

**Comment by ignasi35** [comment]
Resolved in #18
