### ISSUE TITLE
Error while accessing the application

### ISSUE THREAD

**Issue by mghildiy** [lagom/lagom-java-maven-chirper-example#20]
I cloned the project and tried to access the application through browser. I get error as:

> ProvisionException: Unable to provision, see the following errors:

1) No implementation for com.lightbend.lagom.javadsl.server.LagomServiceRouter was bound.
  while locating com.lightbend.lagom.javadsl.server.LagomServiceRouter
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router
    for the 1st parameter of play.api.http.JavaCompatibleHttpRequestHandler.<init>(HttpRequestHandler.scala:217)
  while locating play.api.http.JavaCompatibleHttpRequestHandler
  while locating play.api.http.HttpRequestHandler
    for the 6th parameter of play.api.DefaultApplication.<init>(Application.scala:236)
  at play.api.DefaultApplication.class(Application.scala:235)
  while locating play.api.DefaultApplication
  while locating play.api.Application

1 error

How to handle this issue?

**Comment by ignasi35** [comment]
Hi @mghildiy I think you posted the same error twice by mistake. I'll close this one and leave #19. Thanks
