### ISSUE TITLE
Front end doesn't show up after running mvn lagom:runAll

### ISSUE THREAD

**Issue by vimalmishrra** [lagom/lagom-java-maven-chirper-example#23]
It throws the following error
----------------------------------------
Action Not Found

For request 'GET /'
These routes have been tried, in this order:

1GET\Q/api/users/\E([^/]+)Service: friendservice (http://0.0.0.0:60399)

2POST\Q/api/users\EService: friendservice (http://0.0.0.0:60399)

3POST\Q/api/users/\E([^/]+)\Q/friends\EService: friendservice (http://0.0.0.0:60399)

4GET\Q/api/users/\E([^/]+)\Q/followers\EService: friendservice (http://0.0.0.0:60399)

5POST\Q/api/chirps/live/\E([^/]+)Service: chirpservice (http://0.0.0.0:54485)

6GET\Q/api/chirps/live\EService: chirpservice (http://0.0.0.0:54485)

7GET\Q/api/chirps/history\EService: chirpservice (http://0.0.0.0:54485)

8GET\Q/api/activity/\E([^/]+)\Q/live\EService: activityservice (http://0.0.0.0:51855)

9GET\Q/api/activity/\E([^/]+)\Q/history\EService: activityservice (http://0.0.0.0:51855)
-------------------------------------------

**Comment by ignasi35** [comment]
Hi @vimalmishrra , I just did a clean clone and could use the application. I think there's some error on the terminal where you are trying to run this sample app that will help you determine the cause of the error.

If you still experience issues I suggest you used the https://discuss.lagomframework.com/ forums to ask for extra help.
